# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 350bdbded9842a47104676a96b1d3a6baad99877f45238a45016ca8e977c5b9fdf47ef52da97a306786ee00e35eed2074375c926faf9f18184d27d04208ef217

test:
  secret_key_base: fecf64d62d8bf32f10d97b6961c9c215f891c14c1f7b321444a4326c86c3935a9283ad17d99a6d321549c88524ee2e4bb6f71febc98d9025449f229911f0f748

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
